[package]
name = "rib"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11.3"
log = { version = "0.4.21", features = ["std"] }
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.13"
